// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc_postgres

import (
	"context"
	"time"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO user_credentials (id, user_id, username, method, password, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCredentialParams struct {
	ID        string
	UserID    string
	Username  string
	Method    string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.Method,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO user_profiles (id, name, address, phone, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateProfileParams struct {
	ID        string
	Name      string
	Address   string
	Phone     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getCredentialByUsername = `-- name: GetCredentialByUsername :one
SELECT id, user_id, username, method, password, created_at, updated_at
FROM user_credentials
WHERE username = $1
`

func (q *Queries) GetCredentialByUsername(ctx context.Context, username string) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByUsername, username)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Method,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, name, address, phone, created_at, updated_at
FROM user_profiles
WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id string) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchProfiles = `-- name: SearchProfiles :many
SELECT id, name, address, phone, created_at, updated_at
FROM user_profiles
WHERE (cast($1 as text) = '' OR name ILIKE '%' || cast($1 as text) || '%')
  AND (cast($2 as text) = '' OR phone ILIKE '%' || cast($2 as text) || '%')
ORDER BY created_at ASC
`

type SearchProfilesParams struct {
	Name  string
	Phone string
}

func (q *Queries) SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]UserProfile, error) {
	rows, err := q.db.QueryContext(ctx, searchProfiles, arg.Name, arg.Phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfile
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
