//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Address defines model for Address.
type Address struct {
	Country       string `json:"country"`
	Locality      string `json:"locality"`
	PostalCode    string `json:"postal_code"`
	Region        string `json:"region"`
	StreetAddress string `json:"street_address"`
}

// EnrichRequest defines model for EnrichRequest.
type EnrichRequest struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`

	// Provider Target IdP provider name (e.g. ABC or XYC)
	Provider *string `json:"provider,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// IdentityPII defines model for IdentityPII.
type IdentityPII struct {
	Address Address `json:"address"`
	Name    string  `json:"name"`
	Phone   string  `json:"phone"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// ExpiresIn Token validity duration in seconds
	ExpiresIn int `json:"expires_in"`

	// Token Signed JWT token
	Token     string `json:"token"`
	TokenType string `json:"token_type"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Address  string `json:"address"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Username string `json:"username"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SearchProfilesParams defines parameters for SearchProfiles.
type SearchProfilesParams struct {
	// Name Substring match on profile name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Phone Substring match on phone number
	Phone *string `form:"phone,omitempty" json:"phone,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// EnrichProfileJSONRequestBody defines body for EnrichProfile for application/json ContentType.
type EnrichProfileJSONRequestBody = EnrichRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate credential and obtain JWT bearer token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Register credential and bootstrap profile
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// Search user profiles
	// (GET /profiles)
	SearchProfiles(w http.ResponseWriter, r *http.Request, params SearchProfilesParams)
	// Composed path invoking IdP connector and returning PII to caller
	// (POST /profiles/enrich)
	EnrichProfile(w http.ResponseWriter, r *http.Request)
	// Retrieve a user profile by ID
	// (GET /profiles/{id})
	GetProfileByID(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchProfiles operation middleware
func (siw *ServerInterfaceWrapper) SearchProfiles(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchProfilesParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "phone" -------------

	err = runtime.BindQueryParameter("form", true, false, "phone", r.URL.Query(), &params.Phone)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "phone", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchProfiles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrichProfile operation middleware
func (siw *ServerInterfaceWrapper) EnrichProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrichProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfileByID operation middleware
func (siw *ServerInterfaceWrapper) GetProfileByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfileByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc("GET "+options.BaseURL+"/profiles", wrapper.SearchProfiles)
	m.HandleFunc("POST "+options.BaseURL+"/profiles/enrich", wrapper.EnrichProfile)
	m.HandleFunc("GET "+options.BaseURL+"/profiles/{id}", wrapper.GetProfileByID)

	return m
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse UserProfile

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Register400JSONResponse ErrorResponse

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type SearchProfilesRequestObject struct {
	Params SearchProfilesParams
}

type SearchProfilesResponseObject interface {
	VisitSearchProfilesResponse(w http.ResponseWriter) error
}

type SearchProfiles200JSONResponse []UserProfile

func (response SearchProfiles200JSONResponse) VisitSearchProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchProfiles401JSONResponse ErrorResponse

func (response SearchProfiles401JSONResponse) VisitSearchProfilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type EnrichProfileRequestObject struct {
	Body *EnrichProfileJSONRequestBody
}

type EnrichProfileResponseObject interface {
	VisitEnrichProfileResponse(w http.ResponseWriter) error
}

type EnrichProfile200JSONResponse IdentityPII

func (response EnrichProfile200JSONResponse) VisitEnrichProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EnrichProfile401JSONResponse ErrorResponse

func (response EnrichProfile401JSONResponse) VisitEnrichProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type EnrichProfile502JSONResponse ErrorResponse

func (response EnrichProfile502JSONResponse) VisitEnrichProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileByIDRequestObject struct {
	Id string `json:"id"`
}

type GetProfileByIDResponseObject interface {
	VisitGetProfileByIDResponse(w http.ResponseWriter) error
}

type GetProfileByID200JSONResponse UserProfile

func (response GetProfileByID200JSONResponse) VisitGetProfileByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileByID401JSONResponse ErrorResponse

func (response GetProfileByID401JSONResponse) VisitGetProfileByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileByID404JSONResponse ErrorResponse

func (response GetProfileByID404JSONResponse) VisitGetProfileByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate credential and obtain JWT bearer token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Register credential and bootstrap profile
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Search user profiles
	// (GET /profiles)
	SearchProfiles(ctx context.Context, request SearchProfilesRequestObject) (SearchProfilesResponseObject, error)
	// Composed path invoking IdP connector and returning PII to caller
	// (POST /profiles/enrich)
	EnrichProfile(ctx context.Context, request EnrichProfileRequestObject) (EnrichProfileResponseObject, error)
	// Retrieve a user profile by ID
	// (GET /profiles/{id})
	GetProfileByID(ctx context.Context, request GetProfileByIDRequestObject) (GetProfileByIDResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchProfiles operation middleware
func (sh *strictHandler) SearchProfiles(w http.ResponseWriter, r *http.Request, params SearchProfilesParams) {
	var request SearchProfilesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchProfiles(ctx, request.(SearchProfilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchProfiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchProfilesResponseObject); ok {
		if err := validResponse.VisitSearchProfilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrichProfile operation middleware
func (sh *strictHandler) EnrichProfile(w http.ResponseWriter, r *http.Request) {
	var request EnrichProfileRequestObject

	var body EnrichProfileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnrichProfile(ctx, request.(EnrichProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrichProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnrichProfileResponseObject); ok {
		if err := validResponse.VisitEnrichProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfileByID operation middleware
func (sh *strictHandler) GetProfileByID(w http.ResponseWriter, r *http.Request, id string) {
	var request GetProfileByIDRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfileByID(ctx, request.(GetProfileByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfileByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProfileByIDResponseObject); ok {
		if err := validResponse.VisitGetProfileByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYbW/TQBL+KyvffQCdaZK2KZBvaXlREOiqphV3QlW1scfJgr3rzo4DOZT/fprd2I5j",
	"p6WCVvRDZcfe2Xl55nlm/TOITJYbDZpsMPoZ2GgBmXSX4zhGsO4yR5MDkgJ3F5lCE674En7ILE8hGAVX",
	"03EQBrTK+cYSKj0P1mGQmkiminZenkot3qHUkbKR6VqWG0syvYlMDM2Vr48H/WHXCoS5Mrr58lmnS5YQ",
	"gG5kHV694nh4Ij4pa5XRYkrt1W6j20IhxMHoy66prXArh5qxhFXyrivbZvYVImLP3mpU0eICbguw1M67",
	"ltlONk7NTHwwGmxnDhdG77z/r8FwOHz96uXJ8PiocwmapYoBeVUMiSxSCkbB+PQsCIMYbIQqJ5fl4FLi",
	"HEhM4nNRLhLsn3gGB/MDMT49EwbFf/579vzeJLqwSnc704Jo8AJsbrSFdlqAHzfjLLQsaGFQ/Q/irjgz",
	"sFbOd5Lj6q7n7LfSS5mqWMxAIqAg8w30vXF4P2rjXaFMYtCkaHU+mbQD2ULkPxGSYBT8o1d3Z2/Tmr2y",
	"L9fhoyPirkqFlb9dgX40c6X3IjmX1n43GDd9KX8dHHaCs7CA7YBlqiK41/NqbVjvfYfbe6H2I1cI9kZp",
	"3yGNjmCQCIcbRSsRFyj5iVBaWIiMjrkkld9HJ/1+tb/SBHNAdsBDrWV8quYaYvHh8+U+MG6W3vifG5Bw",
	"IL43RZXd2ky4HXBXui5griwB7i30FqRb/pa1bMN0Cx37MXwnPh6OhrBEd03m+xnpygKeo0lUCnfGXBdh",
	"cHgkPkn8BiSmFIqGAIaiW6giBEkQ30iX2MRgxldBLAlekMqga43a6anB5u9Fx7/yr8tOu9HG3Ghimila",
	"PIRbBodHx8OTl50NnccPjG+njuqOsjXS19irXVAeCiAqUNFqyiTr6+j7ZlzQgu+8FLwrnfzw+bKlidyd",
	"ytoCYjFbiR5LUC9lQhEyIUARITj6l6lYAqpERY4hgtBPXezRbKdXF0R5sGYHlU5MmxfYOzYZcXDi4u30",
	"UozPJyIxyLLM+BQWJEaLHgKhgiUIqWMn205ZrGJDB7yhIle0UqHEeyOmgEsuOpt8NtHEt/BdvFE2KvyM",
	"9G+XQdb4JaD1Pg0O+gd9rq/JQctcBaPg6KB/cOS6jRYut1vJcQ1kPHlwG7mcTOJg5Mk48CUHS6cmXvnx",
	"UxNo977M83STxd5X68c/L5P3iWhDn9ZNYBEW4H7wMuAcPuz3//TeG5Fxm++wfRFFYG1SpELWBeZn6zA4",
	"7g/+mCfNyarDk8lmEKqha327FFkm+QjQQOA2whlmZkZSaadau5OUnFvu4HEzvGu27bGBG2nZD49SfB4J",
	"Ibva9ksg+XOl2ZaYjsKceXKrupzTXWff46T/dDg5lbHAMlG89+un2/tqo+YiMjpJVUnoFULLQu6ic2YM",
	"WUKZl0m8D5eb11yp59CByKmj2vPyNeY7lBkQIBttzXTFzOuayCRFC2F0Vc2NpjE5BrcF4KrUuVEpd3Xu",
	"WhL5K/uwRApdZDPXPl37lCq6f6Pr36RIRZDZB7VBJYsSUa66sPBRWRIm8ZFyyFXNnpo5r7aOoOJZdvfZ",
	"8nljBnFY2Z4+vlxzsmtEe5wJHmPrAGvwVgBswrYH7vPCfkL1nx/Oq2Z4DFZtfuJ4YuHdPn13lOx8MhG2",
	"kt50JcqZKRYJmsxNTUwcCFQgH8fIiEimqT+5/V3och+idjEWBsP+4RM6mVtCkD5xiVRpgfAwoJ+5GZVl",
	"TtKCYzPfOE4/vmoNERncKgk/4yLWdeloijDgSXbucd/qkZ8qXu/l9/dAGzOnq8mb+/j9SqvbAipOVw58",
	"iaoZl4OqCdcdZpq98Jjs+xuzx+aRSEyh47+eWNm946dzr0yONlQm6CGIv6iOaQ165wOlQ1wXxzv7uOxG",
	"4UdHBDEsITV5BppETxBYEn4JH40x3Zw0R72e442FsTR61X/VD9bX6/8HAAD///RuJ2wiGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
