// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc_sqlite

import (
	"time"
)

type UserCredential struct {
	ID        string
	UserID    string
	Username  string
	Method    string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserProfile struct {
	ID        string
	Name      string
	Address   string
	Phone     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
